name: Publish

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
      - name: Publish to crates.io
        run: cargo publish --verbose
